export interface StandardItem {
  is_number: string;
  year: string;
  title_en: string;
  title_hi: string;
  status: "Active" | "Withdrawn";
  scheme: string;
  category: string;
  scope_en: string;
  source_url: string;
  sample_query: string;
}

export interface SchemeItem {
  key: string;
  name_en: string;
  name_hi: string;
  suitable_for: string;
  process_en: string[];
  source_url: string;
  apply_at: string;
}

export const CURATED_STANDARDS: StandardItem[] = [
  {
    is_number: "IS 10500",
    year: "2012",
    title_en: "Drinking Water — Specification",
    title_hi: "पेय जल — विशिष्टि (Peya Jal)",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), BIS recognised lab testing",
    category: "Water & Food",
    scope_en: "Specification for potable water quality — limits for colour, turbidity, pH, chemical and bacteriological parameters. Applies to piped municipal & household water.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "What are the permissible limits and testing requirements under IS 10500:2012 for drinking water?",
  },
  {
    is_number: "IS 14543",
    year: "2016",
    title_en: "Packaged Drinking Water (Other Than Natural Mineral Water)",
    title_hi: "पैकेज्ड पेय जल — विशिष्टि",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory certification",
    category: "Water & Food",
    scope_en: "Packaged drinking water filled into hermetically sealed containers for sale — treatment, packaging, microbial safety, and mandatory labelling.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "Is ISI mark compulsory for packaged drinking water manufacturing plant under IS 14543?",
  },
  {
    is_number: "IS 17803",
    year: "2022",
    title_en: "Insulated Flask / Stainless-Steel Water Bottle",
    title_hi: "इंसुलेटेड फ्लास्क / स्टील पानी बोतल",
    status: "Active",
    scheme: "ISI Mark (Scheme-I); verify Quality Control Order (QCO) before manufacturing",
    category: "Consumer & Household",
    scope_en: "Vacuum insulated stainless-steel flasks and bottles for food contact — material composition (SS 304/316), thermal retention, drop test, and safety markings.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "My startup makes vacuum insulated stainless steel water bottles. Which IS applies and is QCO mandatory?",
  },
  {
    is_number: "IS 16102-1",
    year: "2012",
    title_en: "Self-Ballasted LED Lamps for General Lighting Services",
    title_hi: "एलईडी लैंप सामान्य रोशनी हेतु",
    status: "Active",
    scheme: "Compulsory Registration Scheme (CRS, Scheme-II)",
    category: "Electronics & Lighting",
    scope_en: "Self-ballasted LED lamps for general lighting up to 250V — safety, insulation, temperature rise, and CRS portal registration requirements.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "I manufacture LED bulbs. Which standard applies and is CRS registration required?",
  },
  {
    is_number: "IS 694",
    year: "2010",
    title_en: "PVC Insulated Cables for Working Voltages up to 1100 V",
    title_hi: "1100 V तक पीवीसी इंसुलेटेड केबल",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory under QCO",
    category: "Electrical & Energy",
    scope_en: "PVC insulated unsheathed and sheathed electric cables/cords for domestic and industrial power distribution up to 1100 V.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "What standard covers flexible PVC domestic building wire up to 1100V?",
  },
  {
    is_number: "IS 1293",
    year: "2005",
    title_en: "Plugs and Socket-Outlets for Household and Similar Purposes",
    title_hi: "घरेलू प्लग और सॉकेट (250V)",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory QCO",
    category: "Electrical & Energy",
    scope_en: "Plugs and fixed/portable socket-outlets for AC circuits up to 250 V (6A and 16A configurations) — dimensional compliance, shuttering, and fire retardancy.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "Do domestic 6A and 16A socket outlets require mandatory BIS ISI marking?",
  },
  {
    is_number: "IS 302-1",
    year: "2008",
    title_en: "Safety of Household and Similar Electrical Appliances — General",
    title_hi: "घरेलू बिजली उपकरण सुरक्षा — सामान्य अपेक्षाएं",
    status: "Active",
    scheme: "ISI Mark / CRS depending on specific Part 2 appliance",
    category: "Electrical & Energy",
    scope_en: "General safety against electrical, thermal, and mechanical hazards for household appliances (electric irons, geysers, mixers, refrigerators).",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "What is the overarching safety standard for household electrical appliances under BIS?",
  },
  {
    is_number: "IS 9873-1",
    year: "2019",
    title_en: "Safety of Toys — Mechanical and Physical Properties",
    title_hi: "खिलौनों की सुरक्षा — यांत्रिक गुण",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory QCO for all toys",
    category: "Consumer & Household",
    scope_en: "Safety requirements for toys intended for children under 14 years — mechanical hazards, sharp edges, small parts choke tests, and physical construction.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "What are the mandatory BIS certification requirements for toy manufacturing in India?",
  },
  {
    is_number: "IS 1786",
    year: "2008",
    title_en: "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement",
    title_hi: "कंक्रीट सुदृढ़ीकरण हेतु टीएमटी स्टील सरिया (Fe 500/550)",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory under Steel QCO",
    category: "Civil & Materials",
    scope_en: "Thermo-mechanically treated (TMT) deformed rebar (Fe 415, Fe 500, Fe 550) for reinforced cement concrete structures.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "What is the Indian Standard for Fe 500D TMT reinforcement steel bars?",
  },
  {
    is_number: "IS 269",
    year: "2015",
    title_en: "Ordinary Portland Cement — Specification",
    title_hi: "ऑर्डिनरी पोर्टलैंड सीमेंट (33, 43, 53 ग्रेड)",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory under Cement QCO",
    category: "Civil & Materials",
    scope_en: "Manufacture, chemical and physical requirements for 33, 43, and 53 grade Ordinary Portland Cement.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "Which IS standard governs Ordinary Portland Cement 53 grade?",
  },
  {
    is_number: "IS 4151",
    year: "2015",
    title_en: "Protective Helmets for Two-Wheeler Riders",
    title_hi: "दोपहिया वाहन सुरक्षा हेलमेट",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory under Helmet QCO",
    category: "Safety & Transport",
    scope_en: "Construction, impact absorption, chin strap retention, and optical visor clarity for two-wheeler motorcycle helmets.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "Is ISI mark compulsory for two-wheeler motorcycle helmets under IS 4151?",
  },
  {
    is_number: "IS 2347",
    year: "2017",
    title_en: "Domestic Pressure Cookers — Specification",
    title_hi: "घरेलू प्रेशर कुकर विशिष्टि",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory under Pressure Cooker QCO",
    category: "Consumer & Household",
    scope_en: "Domestic aluminium alloy and stainless steel pressure cookers — burst safety, fusible plug, operating pressure, and heat retention.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "What standard specifies safety devices and operating pressure for domestic pressure cookers?",
  },
  {
    is_number: "IS 2553-1",
    year: "2019",
    title_en: "Safety Glass — Automotive Applications",
    title_hi: "सुरक्षा कांच — ऑटोमोटिव",
    status: "Active",
    scheme: "ISI Mark (Scheme-I), Compulsory QCO",
    category: "Safety & Transport",
    scope_en: "Toughened and laminated safety glass for motor vehicle windscreens, side windows, and rear windows.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "Which Indian Standard covers automotive toughened and laminated safety glass?",
  },
  {
    is_number: "IS 0000-DEMO",
    year: "1999",
    title_en: "Demo Withdrawn Standard (Example for versioning checks)",
    title_hi: "डेमो वापस लिया गया मानक",
    status: "Withdrawn",
    scheme: "None — historical reference only",
    category: "Safety & Transport",
    scope_en: "Demonstration withdrawn standard entry to verify warning alerts for deprecated or superseded standards.",
    source_url: "https://www.bis.gov.in/know-your-standard",
    sample_query: "Can I manufacture products under withdrawn standard IS 0000-DEMO?",
  },
];

export const CERTIFICATION_SCHEMES: SchemeItem[] = [
  {
    key: "ISI",
    name_en: "ISI Mark — Product Certification Scheme (Scheme-I)",
    name_hi: "आईएसआई मार्क — उत्पाद प्रमाणीकरण योजना",
    suitable_for: "Domestic manufacturers producing products under mandatory QCOs or voluntary standards (Cement, Steel, Water, Cookers, Cables, Helmets).",
    process_en: [
      "Identify applicable Indian Standard (IS) and check Quality Control Order (QCO) status.",
      "Establish in-house testing laboratory and quality assurance infrastructure.",
      "Submit online application on the Manakonline portal with technical documents and fees.",
      "Undergo BIS officer factory inspection and sample drawal for lab testing.",
      "Independent testing in a BIS or NABL-accredited recognised testing laboratory.",
      "Grant of CM/L license, followed by authorization to emboss the official ISI mark.",
    ],
    source_url: "https://www.bis.gov.in/product-certification/product-certification-overview/",
    apply_at: "https://www.manakonline.in/",
  },
  {
    key: "CRS",
    name_en: "Compulsory Registration Scheme (CRS, Scheme-II)",
    name_hi: "अनिवार्य पंजीकरण योजना (सीआरएस — इलेक्ट्रॉनिक्स व आईटी)",
    suitable_for: "Electronics and IT goods (e.g., LED lamps, mobile phones, laptops, power adapters, Li-ion batteries) regulated by MeitY / BIS.",
    process_en: [
      "Verify that the electronic/IT equipment is covered in the Ministry CRS gazette schedule.",
      "Submit sample to a BIS-approved testing laboratory in India for safety testing.",
      "Receive certified test report from the laboratory (valid within specified timeline).",
      "Submit online registration application on the BIS CRS portal with test report and manufacturer declarations.",
      "Grant of unique R-Number (no factory inspection required); emboss BIS standard mark with R-XXXXXX.",
    ],
    source_url: "https://www.crsbis.in/BIS/about-crs.do",
    apply_at: "https://www.crsbis.in/BIS/registration-page.do",
  },
  {
    key: "HALLMARK",
    name_en: "Hallmarking Scheme (HUID) — Gold & Silver Jewellery",
    name_hi: "हॉलमार्किंग योजना (एचयूआईडी — स्वर्ण एवं रजत आभूषण)",
    suitable_for: "Jewellery retailers, manufacturers, and consumers verifying purity (14K, 18K, 20K, 22K, 23K, 24K) in mandatory hallmarking districts.",
    process_en: [
      "Jeweller obtains one-time online registration on the Manakonline portal.",
      "Articles sent to an accredited Assaying and Hallmarking Centre (AHC).",
      "AHC conducts fire assay / XRF testing and laser engraves the 6-digit alphanumeric HUID.",
      "Every hallmarked piece carries BIS logo, purity/fineness mark, and unique HUID.",
      "Consumers can authenticate authenticity and jeweller details instantly via the BIS Care mobile app.",
    ],
    source_url: "https://www.bis.gov.in/hallmarking-overview/",
    apply_at: "https://www.bis.gov.in/hallmarking-overview/jewellers-registration-scheme/",
  },
  {
    key: "FMCS",
    name_en: "Foreign Manufacturers Certification Scheme (FMCS)",
    name_hi: "विदेशी निर्माता प्रमाणीकरण योजना",
    suitable_for: "Overseas manufacturing facilities exporting goods into India under mandatory Indian Standards.",
    process_en: [
      "Appoint an Authorised Indian Representative (AIR) residing in India.",
      "Submit formal application accompanied by manufacturing process flows, test facilities, and fees.",
      "BIS delegation conducts on-site factory audit and sample drawal at foreign facility.",
      "Drawn samples tested in BIS laboratories in India.",
      "Grant of CM/L licence upon compliance and payment of marking fees.",
    ],
    source_url: "https://www.bis.gov.in/fmcs/fmcs-overview/",
    apply_at: "https://www.manakonline.in/FMCS/eBISLogin",
  },
];
