"""Search the 24k-row BIS catalogue for retrieval and administration tools.

This module returns candidate records only. Chat replies must be generated by
the configured language model using evidence assembled by the RAG retriever.
"""
from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path

from .allowlist import KYS_PORTAL, safe_public_url

_TOKEN_RE = re.compile(r"[a-z0-9]+", re.IGNORECASE)
_PORTAL = KYS_PORTAL

_STOP = frozenset("""
what does the cover about which with from that this give summary scope standard
indian tell please explain specification requirements requirement information info
is are was were do does did done for on in of to a an the and or my i me we you
your yours how when where who whom it its these those from by as at be been being
have has had will would can could should suggest recommend suitable applicable
for my product startup manufacturing manufacture makes make
""".split())


def _qtoks(query: str) -> set[str]:
    return {w for w in _TOKEN_RE.findall((query or "").lower())
            if len(w) > 2 and w not in _STOP}


def _digits(s: str) -> str:
    m = re.search(r"\d+", s or "")
    return m.group(0) if m else ""


def _fts_match(query_toks: set[str], digits: set[str]) -> str:
    parts = [f'"{t}"' for t in sorted(query_toks) if len(t) > 1]
    parts += [f'"{d}"' for d in sorted(digits)]
    return " OR ".join(parts[:14]) if parts else ""


def _fts_table(conn: sqlite3.Connection) -> bool:
    try:
        row = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
            " AND name='catalogue_fts'").fetchone()
        return row is not None
    except Exception:
        return False


def search_catalogue(query: str, db_path: str | Path | None = None,
                     limit: int = 5, _conn: sqlite3.Connection | None = None) -> list[dict]:
    """Keyword scan of catalogue_standards. [] when DB/table missing.

    Each hit: {standard_id, standard_number, title, department, committee,
    type_name, published_on, source_url, score, exact_match, relevant}.
    """
    from .rag_config import load_rag_config
    db_path = str(db_path or load_rag_config()["db_path"])
    q = (query or "").strip()
    if not q:
        return []
    qt = _qtoks(q)
    qdigits = {d for d in re.findall(r"\d{3,5}", q)}
    if not qt and not qdigits:
        return []
    own_conn = _conn is None
    if _conn is not None:
        conn = _conn
    else:
        if not os.path.exists(db_path):
            return []
        try:
            conn = sqlite3.connect(str(db_path))
            conn.row_factory = sqlite3.Row
        except Exception:
            return []
    try:
        # FTS candidate generation (issue #4 P1-10): MATCH narrows the 24k
        # rows to a small set; Python scoring below keeps exact semantics.
        # Full scan remains the fallback when FTS is missing or silent.
        rows = None
        match = _fts_match(qt, qdigits)
        if match and _fts_table(conn):
            try:
                # BM25 pre-rank keeps rare-term rows (the ones Python
                # scoring promotes) inside the candidate window.
                rows = conn.execute(
                    "SELECT s.standard_id, s.standard_number, s.standard_label,"
                    " s.standard_name, s.department, s.committee, s.type_name,"
                    " s.published_on FROM catalogue_fts"
                    " JOIN catalogue_standards s ON s.standard_id = catalogue_fts.rowid"
                    " WHERE catalogue_fts MATCH ? ORDER BY bm25(catalogue_fts)"
                    " LIMIT 200", (match,)).fetchall()
            except Exception:
                rows = None
        if rows is None:
            try:
                rows = conn.execute(
                    "SELECT standard_id, standard_number, standard_label,"
                    " standard_name, department, committee, type_name, published_on"
                    " FROM catalogue_standards").fetchall()
            except Exception:
                return []
        # source URLs for the indexed (downloaded) subset
        url_by_sid: dict = {}
        try:
            for r in conn.execute(
                    "SELECT standard_id, source_url FROM corpus_documents"
                    " WHERE source_url <> ''"):
                url_by_sid[r["standard_id"]] = r["source_url"]
        except Exception:
            pass
        scored: list[dict] = []
        for r in rows:
            num = r["standard_number"] or ""
            name = r["standard_name"] or ""
            dept = (r["department"] or "") + " " + (r["committee"] or "")
            name_toks = set(_TOKEN_RE.findall(name.lower()))
            dept_toks = set(_TOKEN_RE.findall(dept.lower()))
            num_toks = set(_TOKEN_RE.findall(num.lower()))
            overlap_name = len(qt & name_toks)
            overlap = len(qt & (name_toks | dept_toks | num_toks))
            score = 2.0 * overlap_name + 0.5 * len(qt & dept_toks)
            exact = bool(qdigits and _digits(num) in qdigits)
            if exact:
                score += 20.0
            if score <= 0:
                continue
            relevant = bool(exact or overlap_name >= 2 or overlap >= 3)
            scored.append({
                "standard_id": r["standard_id"],
                "standard_number": num,
                "title": name or r["standard_label"] or num,
                "department": r["department"] or "",
                "committee": r["committee"] or "",
                "type_name": r["type_name"] or "",
                "published_on": r["published_on"] or "",
                "source_url": url_by_sid.get(r["standard_id"], _PORTAL),
                "score": score,
                "exact_match": exact,
                "relevant": relevant,
            })
        scored.sort(key=lambda d: -d["score"])
        return scored[:limit]
    finally:
        if own_conn:
            try:
                conn.close()
            except Exception:
                pass
